version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1122
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/ 

  basketdb:
    container_name: basketdb
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    restart: always
    ports:
      - "5433:5432"  
    volumes:
      - postgres_basket:/var/lib/postgresql/data/ 

  distributedcache:
    container_name: distributedcache
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  catalog.api:
    container_name: catalog_api
    image: my-catalog-api:latest  # Cần build Dockerfile trước
    depends_on:
      - catalogdb
      - distributedcache
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=1122;Include Error Detail=true
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

volumes:
  postgres_catalog:
  postgres_basket:
